### ISSUE TITLE
Migrating to gap-packages

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/sgpdec#1]
We have created new VO at https://github.com/gap-packages and suggest that all GAP packages could eventually migrate there - please consider doing so when it may be appropriate and less disruptive for your package.

**Comment by fingolfin** [comment]
@egri-nagy  any comments on on this? We'd be happy to help you with it... Basically, you need to this:
1. Go to the repository settings at https://github.com/gap-system/sgpdec/settings
2. In the "Danger zone", click on "Transfer ownership"
3. Follow the instructions there (if there are any issues, contact us)
4. Edit any websites or files pointing to https://github.com/gap-system/sgpdec/ to instead point to https://github.com/gap-packages/sgpdec/  (though there should also be an automatic redirect)

**Comment by egri-nagy** [comment]
Done! Sorry for the delay!
