### ISSUE TITLE
DotSemigroupAction and DotSemigroupActionWithNames

### ISSUE THREAD

**Issue by nehaniv** [gap-packages/sgpdec#10]
I have code for these functions that runs with SgpDec 0.7.33  (3 files init.g, dotsemigroupaction.gd and dotsemigroupaction.gi are affective).
I see that the "gap" subdirectory is now "lib".    I want to make these available to students now, so could we have a SgpDec 0.7.34 or should they go to development version.

**Comment by nehaniv** [comment]
I've uploaded the 2 files and edited init.g on a new branch from master.  But might be better to include these changes into a SgpDec 0.7.34.

**Comment by nehaniv** [comment]
also read.g

**Comment by egri-nagy** [comment]
The corresponding pull request has been merged.

**Comment by nehaniv** [comment]
These commands need to show points that are not moved. Currently they are not visualized which can be misleading for visualizing the permutator and holonomy groups.  (e.g. for the lac operon, the top permutator group doesn't mean state 3 (Op) but this state isn't even shown, and also the corresponding holonomy group is trivial, which is visualized as blank graph!).

**Comment by nehaniv** [comment]
OK - I've implemented the required functionality.  Looks great and will help students understand holonomy!   :)
