### ISSUE TITLE
Changing default package test

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/sgpdec#16]
The `PackageInfo.g` file still specifies the old `tst/test.g` script:

https://github.com/gap-packages/sgpdec/blob/bd09e25b80a71688810b64de37dbe722e2da25c6/PackageInfo.g#L109

which is not compatible with tools that I use to run regression tests for GAP packages (e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/jobs/507621275 which clones the current SgpDec repository and tests it with GAP stable-4.10 branch and a corresponding selection of GAP packages). 

Since now `tst/testall.g` is runnable, I suggest that you replace `tst/test.g` by `tst/testall.g` in `PackageInfo.g`. Pergaps you can even delete `tst/test.g`, but that's up to you.

**Comment by olexandr-konovalov** [comment]
P.S. congratulations with https://github.com/gap-packages/sgpdec/releases/tag/v0.9 !

**Comment by egri-nagy** [comment]
I made the change in `PackageInfo.g`. https://github.com/gap-packages/sgpdec/commit/f80b6373f24b9f7fe57daf9109a67ec5a7abd8c9 Let me know whether this solves the problem or not.

Thanks! We continue to work on the documentation, and soon the package will be ready for the submission.

**Comment by olexandr-konovalov** [comment]
Nice - see the beautiful test log at https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/jobs/507621275!
