### ISSUE TITLE
Fix PackageInfo.g, update your various websites and repositories to point to true one location?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/sgpdec#2]
Your `PackageInfo.g` is currently invalid in that various URLs which should point to e.g. copies of the README and `PackageInfo.g` file just say `http://sgpdec.sf.net`.

Also, I find it very confusing there the website is at http://sgpdec.sf.net ; it points to bitbucket; but your bitbucket account seems to be unused (so maybe this is now the official repository after all); on bitbucket in turn you also point people to https://compsemi.wordpress.com/software/sgpdec/ as your website; and then of course there is also https://sourceforge.net/projects/sgpdec/

This leaves me quite confused :-).

**Comment by olexandr-konovalov** [comment]
@egri-nagy you may find useful [ValidatePackageInfo](http://www.gap-system.org/Manuals/doc/ref/chap76.html#X79767C2482FF6F55) and also the validator at the bottom of [this page](http://www.gap-system.org/Packages/Authors/authors.html).

**Comment by egri-nagy** [comment]
Your confusion is well-founded. :)

However, I'm trying to generate pages for SgpDec on github, I don't have access to Settings for the project. Also, I am not able to close issues. Is this the consequence of migrating to gap-packages?

**Comment by fingolfin** [comment]
Yes, after the migration, we then needed to updated your access settings, which I have just done. Please try again!

**Comment by fingolfin** [comment]
Did everything work now? If yes, you can close the issue from my point of view.

Ah, one more minor hint: You can set a package homepage (e.g. pointing to http://gap-packages.github.io/sgpdec) on https://github.com/gap-packages/sgpdec  -- to the right of the repository description at the top of https://github.com/gap-packages/sgpdec, you should see an "Edit" link, which you can click, and it then allows you to provide a website URL.

**Comment by olexandr-konovalov** [comment]
I've just done that ;)

**Comment by fingolfin** [comment]
Yeah, I could've done it, too -- but I deliberately didn't, because I think it's important to let package maintainers do these things for themselves, as (a) it is their package, and (b) only then will they know where this data came from, and how to do it by themselves the next time around... ;-)

**Comment by egri-nagy** [comment]
Thanks a lot! I will have the opportunity to practise that, as I have two more GAP packages to migrate, soon.
