### ISSUE TITLE
`gap makedoc.g` doesn't compile the manual

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/sgpdec#21]
At least as far as I can tell, the 'normal' behaviour of the `makedoc.g` file is that, when the file is read into GAP, the documentation for the package is immediately compiled. Therefore the documentation can be recompiled by calling `gap makedoc.g` when in the package directory (if `gap` is in the `PATH`).

This, for instance, is the way that the GitHub Actions CI is currently set up (see e.g. https://github.com/gap-packages/sgpdec/runs/2304383616?check_suite_focus=true) - and that is the reason why the manual doesn't currently get uploaded as part of the GitHub Actions CI, even though it is intended to.

That said, your `SgpDecMakeDoc` function is documented, and works correctly (as far as I can tell), so there's not really a problem here. It's just that your `makedoc.g` setup is non-standard, and means that your "Build manuals" CI job is not actually building the manual.

**Comment by egri-nagy** [comment]
When the CI job started to fail I finally understood what the problem was.
Thank you for the report, apologies for the slow understanding!
I think c398024 fixes that for now, until implementing a nicer solution - I see that people use AutoDoc now.
