### ISSUE TITLE
group decomposition commands 

### ISSUE THREAD

**Issue by nehaniv** [gap-packages/sgpdec#7]
there is a FL (Frobenius Lagrange Decomposition) command but Perm2Coords is maybe not working anymore I think.    I would like to be able to able to do what's in the cube paper, get coordinate form of a given permutation, and apply LevelKillers.

**Comment by nehaniv** [comment]
Comment: It would be best if coordinates (on states and generators, or possibly other elements) could be obtained, directly from a subgroup chain, without needing to fully decompose into an FLCascade Group, since the latter is computationally hungry.

**Comment by nehaniv** [comment]
Comment:  Easy access to coset reps  written in in terms of generators as short words is highly desirable.   For example, for killing by levels these give the actions (events or generators) to be performed to return to the smallest group in the chain (or identity in the case of a full decomposition).

**Comment by nehaniv** [comment]
While, I'm making this wish list, let me record:

If the bottom group in the subgroup chain stabilizes a point, all the groups above it do to and the orbit of that point decomposes into a nested partition blocks that are coarse-grained translates of the blocks corresponding to the cosets of each level's group.  

So: Being able to see what these blocks consist in the original state space will really help intuition on the hierarchical structure.  E.g. with the pocket cube, the chain Stabilizer(face) < Stabilizer(corner) < PocketCube. The coarse-graining gives: all faces, all corners (disjoint subsets of 3 faces).  
That is, for (G,X) we should add code to give the chain x = x ^Stab(x)=H_n <  x^H_{n-1} < ... < x. G = X, and its translates  x H_i g_{i-1},  with g_{i-1} in H_{i-1} or in G, is in the orbit of the ith block containing x under H_{i-1}, or, respectively, G.

**Comment by egri-nagy** [comment]
The cube paper calculation is now included as a test. So that functionality is definitely there.

**Comment by egri-nagy** [comment]
The issue was partially duplicated in #17. 
The release https://github.com/gap-packages/sgpdec/tree/v0.9.2 closes this issue as well.
Except obtaining short generator sequences on each level, which is more like a research problem.
